name: Deploy
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        permissions:
            id-token: write # Needed for auth with Deno Deploy
            contents: read # Needed to clone the repository

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Build application
              run: deno task build

            - name: Deploy to Deno Deploy
              uses: denoland/deployctl@v1
              with:
                  project: "champions-stories"
                  entrypoint: "server.ts"
                  root: "."
